base_url = "https://narmnevis.github.io"
default_language = "en"
title = "narmnevis"
generate_feeds = true
feed_filenames = ["atom.xml"]
compile_sass = true

[markdown]
[markdown.highlighting]
theme = "solarized-light"
extra_syntaxes_and_themes = []

[languages.fa]
title = "نرم‌نویس"
generate_feeds = true
feed_filenames = ["atom.xml"]

[languages.fa.translations]
home = "خانه"
posts = "نوشته‌ها"
read_more = "بیشتر بخوانید"
